import pygad
import json
SLICE_NAMES = ("eMBB", "URLLC", "mMTC")

kappa = 0.8
Q_28 = 6
R_28 = 0.948
alpha = 1.0

arrival_rates = {
    "eMBB": 50.0,
    "URLLC": 10.0,
    "mMTC": 5.0,
}

##########################################################################################################
# bad fitness value
BAD_FITNESS = [-1e12, -1e12, -1e12, -1e12]
##########################################################################################################
# Global limits check it again from the paper and table 11 and 14 it contain specific contraint for each slice type and also global limits for the resources 
S_max = 300.0 # this is the maximum storage limit for any slice type, we can adjust it based on the actual system capacity and requirements, it should be greater than the maximum storage requirement of any slice type to allow for feasible solutions, we can set it to 200 GB as an example, but it should be adjusted based on the actual system capacity and requirements.
B_max = 300.0 # not mentioned in the paper but we need to set it to a value to check the global limits for bandwidth, we can adjust it based on the actual system capacity and requirements, it should be greater than the sum of the bandwidth requirements of all slices to allow for feasible solutions, we can set it to 100 Mbps as an example, but it should be adjusted based on the actual system capacity and requirements.
C_max = 500.0
P_max = 300.0
##########################################################################################################
# note i should make it more dynamic 
#eMbbslice requirements for MCS 28 in PA phase table 11
L_max_embb_mcs_28_pa = 10 # ms, this is the latency requirement for eMBB slice with MCS 28 table 11
C_max_embb_mcs_28_pa = 200 # this is the cost requirement for eMBB slice with MCS 28 in PA phase  table 11
T_min_embb_mcs_28_pa = 60 # Mbps, this is the throughput requirement for eMBB slice with MCS 28 in PA phase table 11

##########################################################################################################

#URLLC slice requirements for MCS 28 in PA phase table 11
L_max_urllc_mcs_28_pa = 2 # ms, this is
S_max_urllc_mcs_28_pa = 200 # this is the storage requirement for URLLC slice with MCS 28 in PA phase  table 11
T_min_urllc_mcs_28_pa = 5 # Mbps, this is the throughput requirement for URLLC slice with MCS 28 in PA phase table 11
##########################################################################################################
#mMTC slice requirements for MCS 28 in PA phase table 11
L_max_mmtc_mcs_28_pa = 10 # ms, this is the latency requirement for mMTC slice with MCS 28 table 11
S_max_mmtc_mcs_28_pa = 30 # this is the storage requirement for mMTC slice with MCS 28 in PA phase  table 11
T_min_mmtc_mcs_28_pa = 20 # Mbps, this is the throughput requirement for mMTC slice with MCS 28 in PA phase table 11
###########################################################################################################

########################################################## to be replaced with actual candidate solutions generated by the GA, this is just an example structure#####################################################
# step 2 i should add it to the optimization loop and replace it with the actual candidate solutions 
user_requirements = {
    "eMBB": {"bandwidth": 15.0, "compute": 20.0, "power": 10.0, "cost": 8.0},
    "URLLC": {"bandwidth": 12.0, "compute": 18.0, "power": 6.0, "cost": 7.0},
    "mMTC": {"bandwidth": 8.0, "compute": 10.0, "power": 4.0, "cost": 12.0},
}
###########################################################################################################
PHASE_CONSTRAINTS = {
    "PA": {
        "eMBB":  {"throughput_min": 60, "latency_max": 10, "cost_max": 200},
        "URLLC": {"throughput_min": 5,  "latency_max": 2,  "cost_max": 200},
        "mMTC":  {"throughput_min": 20, "latency_max": 10, "cost_max": 30},
    },
    # Fill PB, PC, PD exactly from your paper/table.
}
##########################################################################################################
#note i should replace it with all UES limits and users requirements 
def within_global_limits(candidate, B_max, C_max, P_max, S_max):
    return (
        sum(candidate[s]["bandwidth"] for s in SLICE_NAMES) <= B_max and
        sum(candidate[s]["compute"] for s in SLICE_NAMES) <= C_max and
        sum(candidate[s]["power"] for s in SLICE_NAMES) <= P_max and
        sum(candidate[s]["storage"] for s in SLICE_NAMES) <= S_max
    )
###########################################################################
# Computing functions throughput, latency  cost for each slice type

def compute_throughput(candidate, slice_name):
    # maybe i should make it random to be more realstic and dynamic, but for testing purposes i will use a simple linear function of the allocated bandwidth.
    b = candidate[slice_name]["bandwidth"]
    return kappa * Q_28 * R_28 * b
    
# latency computation for each slice type


def converting_latency_to_milliseconds(latency_s):
    return latency_s * 1000.0


# it return resources allocation for each slice type, we will use it to compute the KPIs for each slice type and check the global limits and user requirements
def decode_solution(solution):
    return {
        "eMBB":  {"bandwidth": solution[0], "compute": solution[1], "power": solution[2], "storage": solution[3]},
        "URLLC": {"bandwidth": solution[4], "compute": solution[5], "power": solution[6], "storage": solution[7]},
        "mMTC":  {"bandwidth": solution[8], "compute": solution[9], "power": solution[10], "storage": solution[11]},
    }

def compute_latency(candidate, slice_name):
    T = compute_throughput(candidate, slice_name) #throughput in bits per second     
    S_pkt = 1500 * 8                         # packet size in bits
    m = (T * 1e6) / S_pkt # service rate in packets per second
    if m <= 0:
        return float('inf')  # Infinite latency if service rate is zero or negative
    L_fix_i = 1 / m  # fixed latency component (transmission time)
    lambda_i = arrival_rates[slice_name]
    rho = lambda_i / (m + 1e-6)
    if rho >= 1.0:
       return float("inf")
    Latency = L_fix_i + 1 / (m * (1 - rho + 1e-6))
    Latency_ms = converting_latency_to_milliseconds(Latency)
    return Latency_ms

def compute_throughput_all(candidate):
    # eMBB
    T_e = compute_throughput(candidate, "eMBB")
    # URLLC
    T_u = compute_throughput(candidate, "URLLC")
    # mMTC
    T_m = compute_throughput(candidate, "mMTC")
    return T_e, T_u, T_m


def compute_cost(candidate, slice_name, alpha):
    c = candidate[slice_name]["compute"]
    s = candidate[slice_name]["storage"]
    print(f"compute: {c}, storage: {s}, alpha: {alpha}, cost: {alpha * (c + s)}")
    return alpha * (c + s) # Cost from compute+storage 

def compute_energy(candidate, slice_name):
    # E_i = p_i
    return candidate[slice_name]["power"]

    #############################################################################################

def aggregate_kpis(candidate, alpha):
    throughput = {s: compute_throughput(candidate, s) for s in SLICE_NAMES}
    latency_ms = {s: compute_latency(candidate, s) for s in SLICE_NAMES}
    cost_eur = {s: compute_cost(candidate, s, alpha) for s in SLICE_NAMES}
    energy = {s: compute_energy(candidate, s) for s in SLICE_NAMES}

    return {
        "throughput": throughput,
        "latency_ms": latency_ms,
        "cost_eur": cost_eur,
        "energy": energy,
        "throughput_total": sum(throughput.values()),
        "latency_total_ms": sum(latency_ms.values()),
        "cost_total_eur": sum(cost_eur.values()),
        "energy_total": sum(energy.values()),
    }


# testbed cpabbilities and user requirements, we will use it to test the fitness function and the structure of the candidate solution
def fitness_func(ga_instance, solution, solution_idx):
    candidate = decode_solution(solution)

    if not within_global_limits(candidate, B_max, C_max, P_max, S_max):
         return BAD_FITNESS

    kpis = aggregate_kpis(candidate, alpha)
    phase = PHASE_CONSTRAINTS["PA"]

    for s in SLICE_NAMES:
        if kpis["throughput"][s] < phase[s]["throughput_min"]:
             print("FAIL throughput", s, kpis["throughput"][s], "<", phase[s]["throughput_min"])
             return BAD_FITNESS
        if kpis["latency_ms"][s] > phase[s]["latency_max"]:
            print("FAIL latency", s, kpis["latency_ms"][s], ">", phase[s]["latency_max"])
            return BAD_FITNESS
        if kpis["cost_eur"][s] > phase[s]["cost_max"]:
            print("FAIL cost", s, kpis["cost_eur"][s], ">", phase[s]["cost_max"])
            return BAD_FITNESS

    return [
         kpis["throughput_total"],
        -kpis["latency_total_ms"],
        -kpis["cost_total_eur"],
        -kpis["energy_total"],
    ]

# gene_space = [
#     {"low": 0.0, "high": B_max}, {"low": 0.0, "high": C_max}, {"low": 0.0, "high": P_max}, {"low": 0.0, "high": S_max},
#     {"low": 0.0, "high": B_max}, {"low": 0.0, "high": C_max}, {"low": 0.0, "high": P_max}, {"low": 0.0, "high": S_max},
#     {"low": 0.0, "high": B_max}, {"low": 0.0, "high": C_max}, {"low": 0.0, "high": P_max}, {"low": 0.0, "high": S_max},
# ]


gene_space = [
    # eMBB
    {"low": 0.0, "high": B_max}, {"low": 0.0, "high": 100.0}, {"low": 0.0, "high": P_max}, {"low": 0.0, "high": 100.0},

    # URLLC
    {"low": 0.0, "high": B_max}, {"low": 0.0, "high": 100.0}, {"low": 0.0, "high": P_max}, {"low": 0.0, "high": 100.0},

    # mMTC
    {"low": 0.0, "high": B_max}, {"low": 0.0, "high": 15.0}, {"low": 0.0, "high": P_max}, {"low": 0.0, "high": 15.0},
]


#B_max it depends on the througtput of the system
# gene_constraint = [
#     bw_constraint("eMBB", tput_min=60, lat_max=10), None, None, storage_cost_constraint(1, 200),
#     bw_constraint("URLLC", tput_min=5,  lat_max=2),  None, None, storage_cost_constraint(5, 200),
#     bw_constraint("mMTC", tput_min=20, lat_max=10), None, None, storage_cost_constraint(9, 30),
# ]

ga_instance = pygad.GA(
    num_generations=80,
    sol_per_pop=60,
    num_parents_mating=10,
    num_genes=12,
    gene_space=gene_space,
    # gene_constraint=gene_constraint,
    fitness_func=fitness_func,
    parent_selection_type="nsga2",
    mutation_percent_genes=10,
    crossover_probability=0.1
)

ga_instance.run()
# do not generate by random solution and then decode it to get the KPIs, instead directly use the candidate solution example_candidate to compute the KPIs and check the global limits, this is just for testing the functions and the structure of the candidate solution, in actual implementation we will use the solutions generated by the GA and decode them to get the user required KPIs and check the global limits, so we will replace the example_candidate user requirments 
solution, solution_fitness, solution_idx = ga_instance.best_solution(ga_instance.last_generation_fitness)
candidate = decode_solution(solution)
kpis = aggregate_kpis(candidate, alpha)
print("Best solution:", solution)
print("Best fitness:", solution_fitness)
print("Decoded candidate:", candidate)
print("Best candidate KPIs:", kpis)
print("Best candidate within limits:", within_global_limits(candidate, B_max, C_max, P_max, S_max))
#######################################################################################################################################################################################################

result = {
    "resources": {
        "best_resources_vector": [float(x) for x in solution],
        "best_fitness": [float(x) for x in solution_fitness],
        "best_resources_by_slice": {
            slice_name: {k: float(v) for k, v in values.items()}
            for slice_name, values in candidate.items()
        }
    },
    "global_limits": {
            "bandwidth_max": float(B_max),
            "compute_max": float(C_max),
            "power_max": float(P_max),
            "storage_max": float(S_max),
    },
     "phase_constraints": {
        "PA": {
            "eMBB": {
                "throughput_min": float(PHASE_CONSTRAINTS["PA"]["eMBB"]["throughput_min"]),
                "latency_max": float(PHASE_CONSTRAINTS["PA"]["eMBB"]["latency_max"]),
                "cost_max": float(PHASE_CONSTRAINTS["PA"]["eMBB"]["cost_max"]),
            },
            "URLLC": {
                "throughput_min": float(PHASE_CONSTRAINTS["PA"]["URLLC"]["throughput_min"]),
                "latency_max": float(PHASE_CONSTRAINTS["PA"]["URLLC"]["latency_max"]),
                "cost_max": float(PHASE_CONSTRAINTS["PA"]["URLLC"]["cost_max"]),
            },
            "mMTC": {
                "throughput_min": float(PHASE_CONSTRAINTS["PA"]["mMTC"]["throughput_min"]),
                "latency_max": float(PHASE_CONSTRAINTS["PA"]["mMTC"]["latency_max"]),
                "cost_max": float(PHASE_CONSTRAINTS["PA"]["mMTC"]["cost_max"]),
            }
        }
    },
    
    "kpis": {
        "throughput": {k: float(v) for k, v in kpis["throughput"].items()},
        "latency_ms": {k: float(v) for k, v in kpis["latency_ms"].items()},
        "cost_eur": {k: float(v) for k, v in kpis["cost_eur"].items()},
        "energy": {k: float(v) for k, v in kpis["energy"].items()},
        "throughput_total": float(kpis["throughput_total"]),
        "latency_total_ms": float(kpis["latency_total_ms"]),
        "cost_total_eur": float(kpis["cost_total_eur"]),
        "energy_total": float(kpis["energy_total"]),
    },
    "within_global_limits": bool(within_global_limits(candidate, B_max, C_max, P_max, S_max)),
 
}


print(json.dumps(result, indent=4))